### ISSUE TITLE
Mistakenly pressed Stop Red button on bottom left side on Profit Trailer - HELP!

### ISSUE THREAD

**Issue by glorianr** [CryptoGnome/Profit-Trailer-Settings#21]
I mistakenly hit stop red button on the bottom left on profit trailer and don't know how to restart the bot.  Can someone help me fix this issue....

**Comment by Stein276** [comment]
Close the command window and restart the bot as you normally would.

**Comment by glorianr** [comment]
Stein276...thank you but it didn't work..not sure what i am doing wrong..

**Comment by Stein276** [comment]
Glad it's working again.
