### ISSUE TITLE
My Bot isnt trading :(

### ISSUE THREAD

**Issue by YugenPh** [CryptoGnome/Profit-Trailer-Settings#22]
My config says OFF at the top. Should this say ON?

**Comment by agaji** [comment]
Mine isn't making buys either . .it's been happening all day. A few people have reported this. Nothing i do gets it to make buys

**Comment by YugenPh** [comment]
@agaji I figured it out! use this http://localhost:8081/settings/overrideSellOnlyMode?enabled=false
