### ISSUE TITLE
my bot is having problem

### ISSUE THREAD

**Issue by yomilad** [CryptoGnome/Profit-Trailer-Settings#4]
My bot is displaying this message "there was an error while refreshing the data. Please check your VSP / PT connection" could it be because of the settings?

**Comment by allanratpupie** [comment]
Make sure that your api key and secret are correct and also make sure that the cmd window is running which means that the bot is running. Hopefully this helps you!

**Comment by shuggiebear1** [comment]
Hello..i am having the same problem. I am not on a VPS , i am on a secure wifi? I cant get this red flashing box off my profit trailer
