### ISSUE TITLE
Extend configs to support POLONIEX

### ISSUE THREAD

**Issue by christoph-buente** [CryptoGnome/Profit-Trailer-Settings#6]
I'm modified the BITTREX config slightly to run my bot in POLONIEX. Happy to contribute.

**Comment by MrSiNiSt3R** [comment]
care to share?

**Comment by xARNALx** [comment]
where is it? i'm interested!! thx for share and contribute!! 👍

**Comment by christoph-buente** [comment]
I'd love to provide a PR, but i don't see any code in the repo, except the releases.

**Comment by MrSiNiSt3R** [comment]
Wrong link... look in Discord #strategies


2018-01-02 11:25 GMT+01:00 Christoph Bünte <notifications@github.com>:

**Comment by christoph-buente** [comment]
@MrSiNiSt3R there is no channel #strategies or at least not visible to me.

**Comment by MrSiNiSt3R** [comment]
The configs are posted by CryptoGnome (my bad "#settings) is it @  - Yesterday at 7:04 PM
not that i want to make you look for it, but since himself closed the topic, while no one answered... anyhow... questions answered, problem solved. If it's worth the little effort, up to you.
