### ISSUE TITLE
No Buying

### ISSUE THREAD

**Issue by Scoby1knoby** [CryptoGnome/Profit-Trailer-Settings#8]
Hi
Bot been running for 12 hrs with V7.0 moderate setting. it has sold coins I had in Bittrex but not bought anything...is there a problem?

**Comment by PeerDeluxe** [comment]
I have the same problem.

**Comment by Vicentewnunes** [comment]
Same here...

**Comment by Scoby1knoby** [comment]
I found that increasing the trading pairs to 10 has helped...Finally getting buys
